### ISSUE TITLE
Bug in table instance alias handling

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/deriva-py#134]
Recent changes have introduced a regression in use of table instance aliases in datapath.

When a path is built up using table instances like `builder.SNAME.TNAME.alias('talias')` and then columns are looked up via `path.talias.cname` (i.e. for filter predicates or attribute projection), the column references in the generated ERMrest URL lack the proper _talias_ qualifier. Instead, they appear _tname_ qualified.

**Comment by robes** [comment]
I just pushed a commit that should fix this. Please let me know if you can test it.

**Comment by karlcz** [comment]
Yes, latest master version works w/ same client code that was exposing this problem.
