### ISSUE TITLE
Authentication token expires even with --refresh

### ISSUE THREAD

**Issue by PratikSinghavi** [informatics-isi-edu/deriva-py#135]
The following command was used to create an authentication cookie on dev:
```
deriva-globus-auth-utils login --refresh --no-browser --hosts dev.rebuildingakidney.org
```

**Expected**: The token should not expire unless revoked or the user logs out.

**Actual** : The token expired even though the user did not logout or revoke the token.

**Comment by mikedarcy** [comment]
This issue has been addressed with the merge of PR #136 .
