### ISSUE TITLE
GEO module - check data types

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/deriva-py#146]
In some cases (e.g. https://www.gudmap.org/id/W-R9JW@2W4-KWT6-DY9C), a GEO export fails, resulting in a 502

```
[TypeError] object of type 'bool' has no len()
```

probably because a column that was previously a text column is now boolean. Fix this particular problem and check the other columns used by the GEO module for similar errors.

**Comment by hongsudt** [comment]
I am closing the issue, as this has been fixed to work on gudmap/rbk.
