### ISSUE TITLE
GEO module - handle null values correctly

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/deriva-py#147]
In some cases (e.g., https://www.gudmap.org/id/17-DS7J@2W4-KWT6-DY9C), GEO exports fail with:

```
[AttributeError] 'NoneType' object has no attribute 'get'
```

Handle null values appropriately (i.e., fail if the null value means some necessary fields will be missing from the GEO object, or set output values to null instead of dereferencing a null pointer)

**Comment by hongsudt** [comment]
I am closing the issue as this problem has been resolved for rbk/gudmap.
