### ISSUE TITLE
Possible Build Catalog in LocalHost?

### ISSUE THREAD

**Issue by cloudlakecho** [informatics-isi-edu/deriva-py#161]
Thanks you for sharing source code of Deriva framework. 

I try to build a catalog in my local computer. I found [the Your First Catalog]( https://docs.derivacloud.org/users-guide/project-tutorial.html#your-first-catalog) example with a remote server.  For the local machine, I changed in the code:
&nbsp;&nbsp;&nbsp;&nbsp; "https" ---> "http"
&nbsp;&nbsp;&nbsp;&nbsp; "severname" ---> "127.0.0.1:8000" (also tried port 80)
&nbsp;&nbsp;&nbsp;&nbsp; "credential" ---> None

and I made "ermrest/catalog" folder where I ran a local host using `$ python -m http.server` in Terminal. 

but my code throw a silent error (at `server = DerivaServer('http', info['servername'], info['credentials'])` code line). 

How could I build a catalog in my local machine? Should I modify other parameter or put different "credential" in the code?  

Here is my snippet as reference:
```
    from deriva.core import DerivaServer, ErmrestCatalog, HatracStore, AttrDict

    info = dict()
    info['credentials'] = None
    
    # (1) Run local server
    #     Open Terminal
    #     $ python -m http.server
    
    # (2) Build a catalog
    info['servername'] = "127.0.0.1:8000"
   
    try: 
        server = DerivaServer('http', info['servername'],
                          info['credentials'])
    except Exception as e:
        print (e.args)
        pdb.set_trace()
 
    try:
        catalog = server.create_ermrest_catalog()
    except Exception as e:
        print (e.args)
        pdb.set_trace()
```

Runtime Environment:
&nbsp;&nbsp;&nbsp;&nbsp; OS: Ubuntu 18.04
&nbsp;&nbsp;&nbsp;&nbsp; Python: 3.8

**Comment by mikedarcy** [comment]
Hi @cloudlakecho.

The `deriva-py` APIs are primarily _client side_ APIs. The `DerivaServer` class is actually a high-level client-side interface for connecting to a an ERMRest catalog. Granted, the name of the class makes this a bit confusing.

Setting up the backend components for a full Deriva stack requires a non-trivial amount of systems administration work. There are multiple python-based software components that are run under Apache HTTPD using `mod_wsgi` and these must be installed and configured properly for the system to function, and the steps to do this can vary based on the operating system type.

If you are only interested in exploring the client APIs to experiment with creating and modifying catalogs, we maintain a tutorial server at https://tutorial.derivacloud.org. You can use this remote instance to test out the full set of Deriva features including catalog, object storage, and authentication features.

In order to create catalogs on this system, you must login with [Globus](https://globus.org) and then request access to the following Globus access [group](https://app.globus.org/groups/ed41a320-8345-11ea-b546-0a875b138121/about).

Next, you will need to login to the tutorial server via a CLI program in order to obtain a `credential` that can be used with the `deriva-py` APIs that required authenticated access. You can use the following command to do this:

```sh
deriva-globus-auth-utils login --host tutorial.derivacloud.org
```

Once you have successfully logged in and have a credential, you can use the following code (similar to what you posted above) to connect to the server and create a catalog.

```python
from deriva.core import DerivaServer, get_credential, format_exception

servername = "tutorial.derivacloud.org"
try:
    server = DerivaServer("https", servername, get_credential(servername))
    catalog = server.create_ermrest_catalog()
    print("Catalog created: %s" % catalog.catalog_id)
except Exception as e:
    print(format_exception(e))
```

Now you should be able to use the returned `catalog` object to continue with the [Your First Catalog](https://docs.derivacloud.org/users-guide/project-tutorial.html#your-first-catalog) tutorial steps.

Note that you need only call `DerivaServer.create_ermrest_catalog()` once to create a catalog. You should then use `DerivaServer.connect_ermrest()` to connect to the `catalog_id` created by the initial `create_ermrest_catalog` call, if you plan on referencing that catalog from other programs or processes.

**Comment by cloudlakecho** [comment]
@mikedarcy Thanks for detailed information, weblink and instruction. 

From your explanation, I have two questions and one related to second question:
&nbsp;&nbsp; If I want to build a Dervia Catalog in:
&nbsp;&nbsp;&nbsp;&nbsp; My local computer/server
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I need to install multiple python-based software components that are run under Apache HTTPD
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Do you have any instruction for setting backend? I like to see how much task involved. 

&nbsp;&nbsp;&nbsp;&nbsp; In remote server, such as https://tutorial.derivacloud.org, I need to have an account in the Globus. Is correct? 
&nbsp;&nbsp;&nbsp;&nbsp; If yes, the instance of "catalog" will be in the remote server (not in my local computer)?

**Comment by mikedarcy** [comment]
For your first question, see https://github.com/informatics-isi-edu/ermrest. There are installation instructions for RedHat OS derivatives linked to on that page. Note that these instructions do not include installation procedures for the Hatrac object store component. 

For your second question, you need only login with Globus as the OAuth security provider. You can use any existing Google account, ORCID account, or institutional account listed in the Globus Auth provider list. You can also create a Globus ID which is essentially creating a bespoke identity for accessing Globus-related resources. 

Finally, yes, catalogs (and the corresponding data) you create on tutorial.derivacloud.org are stored on that remote system and not your local system.

**Comment by cloudlakecho** [comment]
@mikedarcy Thanks for the answers.

**Comment by cloudlakecho** [comment]
@mikedarcy I followed the step but I couldn't get credential. 

Here are my step:
&nbsp;&nbsp; (1) Log in Globus.org (using the Internet browser) 
&nbsp;&nbsp; (2) Make "client_secret_globus.json" in "/home/secrets/oauth2" (followed [code help](https://github.com/informatics-isi-edu/deriva-py/blob/master/deriva/core/utils/globus_auth_utils.py#L25) and [parsing](https://github.com/informatics-isi-edu/deriva-py/blob/master/deriva/core/utils/globus_auth_utils.py#L760-L762))
&nbsp;&nbsp;&nbsp;&nbsp; {
&nbsp;&nbsp;&nbsp;&nbsp;    "web": {
&nbsp;&nbsp;&nbsp;&nbsp;        "client_id": "intellisense@globus.org",
&nbsp;&nbsp;&nbsp;&nbsp;        "client_secret": my password in Globus.org
&nbsp;&nbsp;&nbsp;&nbsp;    }
&nbsp;&nbsp;&nbsp;&nbsp; }
&nbsp;&nbsp; (2) Run `deriva-globus-auth-utils login --host tutorial.derivacloud.org` in Terminal

I am having this message: 

2022-10-10 14:56:24,522 - WARNING - Retrying (Retry(total=9, connect=2, read=4, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)'))': /authn/discovery

Please, let me know if I am doing incorrectly or missing any step. 

Thanks you.

**Comment by cloudlakecho** [comment]
@mikedarcy Thanks for the information. 

I am trying to interact with the actual remote system at tutorial.derivacloud.org to build a catalog in there (not in my local machine). 

Thanks for giving [the correct Internet address](https://tutorial.derivacloud.org/). I thought I have to login with [Globus](https://globus.org/) from your instruction. I will try again.

**Comment by cloudlakecho** [comment]
@mikedarcy  Thanks for continuous guide for building a remote catalog. With you detailed instruction, I could build a (empty) catalog in remote location. 

I am having trouble to add schema and table in the catalog. 

I followed [Deriva tutorial](https://docs.derivacloud.org/deriva-py/README.html#add-table-to-schema) with a few code change. My current guess is that I couldn't build new schema and add table to the schema in one computer code...

Here is error message:
```
  (.venv_3_8) $ python remote_catalog.py
  .../.venv_3_8/lib/python3.8/site-packages/portalocker/utils.py:210: UserWarning: timeout has no effect in blocking mode
    warnings.warn('timeout has no effect in blocking mode')
  Catalog created: 20
  requests.exceptions.HTTPError: 409 Client Error: Conflict for url: [https://tutorial.derivacloud.org/ermrest/catalog/20/schema/micro%20scopic%20image/table] Details: b'409 Conflict\nThe request conflicts with the state of the server. Schema Foreign Schema does not exist.\n'
```

When I read the catalog, it actually has the schema, "micro scopic image". (reading using [DataPath Example 2](https://docs.derivacloud.org/deriva-py/derivapy-datapath-example-2.html)):
```
protocol = 'https'
hostname = 'tutorial.derivacloud.org'
catalog_number = 20
credential = get_credential(hostname)

catalog = ErmrestCatalog(protocol, hostname,
                         catalog_number, credential)
model_root = catalog.getCatalogModel()

pb = catalog.getPathBuilder()
model_path.schemas.keys()
print(pb.schemas.keys())
dict_keys(['public', 'My new schema'])
```
and it looks like I could make a table at this stage (when I read the catalog...not make). 

These are all modification of the [Deriva tutorial](https://docs.derivacloud.org/deriva-py/README.html#add-table-to-schema):
```
schema = model_root.create_schema({"schema_name": "My new schema"}) 
schema = model_root.create_schema({"schema_name": label['schemaname']})

constraint_names=[ [schema_name, "My New Table_Col1_key"] ]
constraint_names=[ [label['schemaname'], "My New Table_Col1_key"] ]

constraint_names=[ [schema_name, "My New Table_Col2_fkey"] ]
constraint_names=[ [label['schemaname'], "My New Table_Col2_fkey"] ]

schema = model_root.schemas[schema_name]
schema = model_root.schemas[label['schemaname']]
```

It looks like that I have an error at `new_table = schema.create_table(table_def)` (at the last line in the code below). Would you indicate where I make mistakes? 

Here is my entire code (mostly from [Deriva tutorial](https://docs.derivacloud.org/deriva-py/README.html#add-schema-to-catalog)) .

To add schema and table in catalog (this is called after catalog made - followed snippet): 
```
def add_schema_custom(model_root=None, label=None):
    schema = model_root.create_schema({'schema_name': label['schemaname']})

    column_defs = [
          em.Column.define("Col1", typ.text),
          em.Column.define("Col2", typ.int8),
        ]

    key_defs = [
          em.Key.define(
                ["Col1"], # this is a list to allow for compound keys
                constraint_names=[ [label['schemaname'],
                                    "My New Table_Col1_key"] ],
                comment="Col1 text values must be distinct.",
                annotations={},
          )
        ]

    fkey_defs = [
          em.ForeignKey.define(
                ["Col2"], # this is a list to allow for compound foreign keys
                "Foreign Schema",
                "Referenced Table",
                ["Referenced Column"], # this is a list to allow for compound k\
eys
                on_update='CASCADE',
                on_delete='SET NULL',
                constraint_names=[ [label['schemaname'],
                                    "My New Table_Col2_fkey"] ],
                comment="Col2 must be a valid reference value from the domain t\
able.",
                acls={},
                acl_bindings={},
                annotations={},
          )
        ]

    table_def = em.Table.define(
          "My New Table",
          column_defs,
          key_defs=key_defs,
          fkey_defs=fkey_defs,
          comment="My new entity type.",
          acls={},
          acl_bindings={},
          acl_bindings={},
          annotations={},
          provide_system=True,
        )

    schema = model_root.schemas[label['schemaname']]

    new_table = schema.create_table(table_def)       
```

To build a catalog at "tutorial.derivacloud.org". This snippet looks like working as expected (the reading code is under.)  

```
info['servername'] = "tutorial.derivacloud.org"
info['schemaname'] = "micro scopic image"

server = DerivaServer("https", info['servername'],
   get_credential(info['servername']))
catalog = server.create_ermrest_catalog()
print("Catalog created: %s" % catalog.catalog_id)

model = catalog.getCatalogModel()
add_schema_custom(model_root=model, label=info)

```

Reading a catalog:
```
protocol = 'https'
hostname = 'tutorial.derivacloud.org'
catalog_number = 20
credential = get_credential(hostname)

catalog = ErmrestCatalog(protocol, hostname,
                         catalog_number, credential)
model_root = catalog.getCatalogModel()

pb = catalog.getPathBuilder()
model_path.schemas.keys()
print(pb.schemas.keys())
```

**Comment by karlcz** [comment]
As the error message says, the columns in your foreign key definition do 
not have matching types.  Your column in your table is type int8, while 
the ID column in the ERMrest_Client table is type text.  You would need 
a text column if you want to form foreign keys to that existing table.

**Comment by cloudlakecho** [comment]
@karlcz Thanks for the suggestion. To clarify your solution:
&nbsp;&nbsp; Should I change column "Col2" from int8 to text in "column_defs"? 
&nbsp;&nbsp; or 
&nbsp;&nbsp; I use "Col1" (which is text form) instead of "Col2" in "fkey_defs" first parameter?

**Comment by karlcz** [comment]
That would depend on whether you want to put a client ID in Col1 or Col2...
