### ISSUE TITLE
Map arbitrary names to identifiers in datapath

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/deriva-py#36]
Rather than pushing modelers to use programmer-style identifiers for table and column names, I think we should make sure that all elements can get equal treatment in the Python API.  If you map any names to identifiers, I think you should also apply a mangling routine to create a valid identifier that acts as a proxy for any names which themselves are not valid identifiers.  That way, a user gets tab-completion for the complete model rather than a subset.

For example, you might:
- Prepend something to names beginning with a digit, since digits are not valid identifiers
- Replace invalid punctuation or whitespace with underscores
- Prepend something to names beginning with underscores to avoid clashing with builtin Python signatures?
- Append some disambiguator if mangled names collide

Ideally, I also think the Python API should use a sub-object to contain these model names as attributes, rather than mashing them into the same object namespace as other API functions...

**Comment by robes** [comment]
Yeah, overall I agree with this.

**Comment by robes** [comment]
Ugh, sorry this went unresolved for so long. I plan to fix this next week.

**Comment by robes** [comment]
This is my take on your outline above:

    1. if object name is a valid identifier and does not conflict with reserved names, use it as is
    2. if object name conflicts with reserved names, prepend with 'id_'
    3. if object name is not a valid identifier,
        a. prepend name with 'id_'
        b. replace non-identifier characters with '_'
        c. if the new name conflicts with other names, append a number to disambiguate

where 'reserved' are the properties (methods, variables) of the python object itself.
