### ISSUE TITLE
Setting comments for tables and columns

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/deriva-py#37]
There is currently an interface for retrieving the comment associated with a table, however, it does not appear that there is a way to set a comment.  This should be added along with methods to set comments on columns as well.

**Comment by karlcz** [comment]
This is now available.  There is a `self.comment` getter and setter for schema, table, column, key, and foreign key constraint objects.  The hierarchical `self.apply()` method will apply the change to the server, like it does for ACLs and annotations.
