### ISSUE TITLE
Clone catalog not working with new Ermrest_Group table.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/deriva-py#63]
Using the clone catalog function generates the following error:

requests.exceptions.HTTPError: 409 Client Error: Conflict for url: [https://pbcconsortium.isrd.isi.edu/ermrest/catalog/10/schema] Details: b'409 Conflict\nThe request conflicts with the state of the server. Referenced columns frozenset({<ermrest.model.Column :public:ERMrest_Group:URL>, <ermrest.model.Column :public:ERMrest_Group:Display_Name>, <ermrest.model.Column :public:ERMrest_Group:Description>, <ermrest.model.Column :public:ERMrest_Group:ID>}) are not part of a unique key.\n'

**Comment by karlcz** [comment]
In your source catalog, did you modify the definition of the `ERMrest_Group` table (adding a compound key)?

If so, I think I understand the problem.  The clone-catalog mechanism is written to be idempotent and creates missing destination tables but does not attempt to modify the "core" definition of existing definition tables. Currently, the "core" definition includes its columns and keys.  So, any additional columns or key definitions in the source catalog will not be propagated to the destination if the destination table already exists...

**Comment by karlcz** [comment]
An enhancement to try to cover these cloning scenarios is now merged to master. Please try it out and reopen this issue if it doesn't cover your use case too...
