### ISSUE TITLE
ErmrestCatalog does not expose catalog id publicly

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/deriva-py#71]
It has a pythonic private `_catalog_id` member. I suggest we add a `catalog_id` read-only property.

This seems useful in general but particularly when you use `DerivaServer` to create a new catalog you get back a catalog object but you can't get the catalog_id for future reference, unless I'm mistaken.

**Comment by carlkesselman** [comment]
Yea…..

I’ve been doing this by getting the catalog URL (which is a public member) and then using urlparse to pull out the catalog id, which is a pain.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Apr 29, 2019, at 6:34 PM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:


It has a pythonic private _catalog_id member. I suggest we add a catalog_id read-only property.

This seems useful in general but particularly when you use DerivaServer to create a new catalog you get back a catalog object but you can't get the catalog_id for future reference, unless I'm mistaken.

**Comment by robes** [comment]
Even `self._server_uri` is private (in a pythonic sense).

**Comment by carlkesselman** [comment]
Right.  I use:


p = urlparse(self.catalog.getCatalogModel().get_server_uri())
catalog_id = p.path.split('/')[-1]

However, I agree, it would be better to just have a function that returns the catalog id.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Apr 29, 2019, at 6:49 PM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:


Even self._server_uri is private (in a pythonic sense).

**Comment by robes** [comment]
OK. I forgot about that method.

Minor nit: that should be a python property getter rather than `get_...()` method.
