### ISSUE TITLE
Column names not urlencoded in ermrest requests

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/deriva-py#9]
This failed request was generated by a call to a CatalogSchema object's apply() method:

"PUT /ermrest/catalog/2/schema/RNASeq/table/Single_Cell_Metrics/column/Reads/Cell/annotation HTTP/1.1" 400 97

The column's name is "Reads/Cell", so I think that part of the URL should have been `Reads%2FCell`, not `Reads/Cell`.

**Comment by karlcz** [comment]
I think this is due to deriva/core/__init__.py importing
urllib.urlquote and exposing it directly instead of overloading it
like we do in other projects.  We need something like:

    def urlquote(s):
       return urllib.urlquote(s, safe='')

because the standard urllib.urlquote oddly assumes that you wouldn't
want to quote a `/` character...

**Comment by karlcz** [comment]
This was fixed by overriding the urlquote function as described above.
