### ISSUE TITLE
Support binning in datapath

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/deriva-py#94]
It would be useful to be able to use the ermrest `bin(` _column_ `;` _nbins_ `;` _minval_ `;` _maxval_ `)` pseudo aggregate function in datapath attributegroups.

Usage might look something like:

```
path.attributegroups(
  {
    'column1': path.talias.column1,
    'bin': Bin(path.talias.column2, nbins, minval=x),
  },
  cnt=Cnt(path.talias.column3)
)
```
Note, these `bin()` funcs are idiomatically used in the group key and so an output alias for the column also must be specified somehow!

This would turn into a URL like you would expect:

`/attributegroup/...path.../talias:column1,bin:=bin(talias:column2;nbins;minval;maxval);cnt:=cnt(talias:column3)`

As a convenience: if the minval/maxval is `None`, do a query behind the scenes to get the current value range:

```
path.aggregate(minval=Min(path.talias.column2), maxval=Max(path.talias.column2)
```

If the bounds are still null after all that, raise a ValueError since ermrest will require a well-defined range in order for the binned query to work.

**Comment by robes** [comment]
I committed what should be called "basic support" for binning where the minval/maxval are required fields. I can probably fetch the minval/max value if they are not given, but I'll have to look at the code a little longer.
